[env:lilygo-t-display]
platform   = espressif32@6.5.0
board      = esp32dev
framework  = arduino
upload_speed = 115200
monitor_speed = 115200

build_flags =
    -DSMOOTH_FONT=1
    -DSPI_FREQUENCY=27000000

lib_deps =
    https://github.com/ESP32Home/TFT_eSPI_ttgo_t-display.git#2.3.4_t-display
    bblanchon/ArduinoJson @ ^7.0.3

[env:usb]
extends = env:lilygo-t-display
upload_port = /dev/ttyACM0
